version: '3'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - '$PORT:$PORT'
    env_file:
      - .env
    command: bash -c "npm run start:$API_START_ARG"
    networks:
      - containers-network
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - containers-network
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-db-data:
    driver: local
networks:
  containers-network:
