version: '3'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - '$PORT:$PORT'
    env_file:
      - .env
    command: bash -c "npm run start:$API_START_ARG"
    networks:
      - containers-network
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - containers-network
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - '$DB_PORT:$DB_PORT'
    command: postgres -c 'max_connections=200' -c 'shared_buffers=512MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'log_statement=all' -c 'max_wal_senders=0' -c 'max_prepared_transactions=0' -c 'random_page_cost=1.0' -c 'log_temp_files=-1' -c 'lc_messages=C.UTF-8' -c 'lc_monetary=C.UTF-8' -c 'lc_numeric=C.UTF-8' -c 'lc_time=C.UTF-8' -c 'log_timezone=UTC' -c 'timezone=UTC'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-db-data:
    driver: local
networks:
  containers-network:
